{application,elixir_scope,
             [{modules,['Elixir.ElixirScope',
                        'Elixir.ElixirScope.AIIntegration',
                        'Elixir.ElixirScope.CodeTracer',
                        'Elixir.ElixirScope.MessageInterceptor',
                        'Elixir.ElixirScope.PhoenixTracker',
                        'Elixir.ElixirScope.ProcessObserver',
                        'Elixir.ElixirScope.QueryEngine',
                        'Elixir.ElixirScope.StateRecorder',
                        'Elixir.ElixirScope.TestSupport.TestCallbackChecker',
                        'Elixir.ElixirScope.TraceDB']},
              {optional_applications,[phoenix,phoenix_live_view]},
              {applications,[kernel,stdlib,elixir,logger,runtime_tools,
                             telemetry,phoenix,phoenix_live_view]},
              {description,"ElixirScope: Advanced Introspection and Debugging for Phoenix Applications\n\nA state-of-the-art Elixir introspection and debugging system with special focus\non Phoenix applications. It enables comprehensive tracking of processes, message\npassing, and state changes with AI-assisted analysis capabilities.\n"},
              {registered,[]},
              {vsn,"0.1.0"}]}.
